package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Default theme
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * ManhwaSlime brand palette: deep navy surfaces with violet, blue, and teal accents.
 */
internal object TachiyomiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFAA8BFF),
        onPrimary = Color(0xFF1B0753),
        primaryContainer = Color(0xFF45218E),
        onPrimaryContainer = Color(0xFFE8DCFF),
        inversePrimary = Color(0xFF6942D8),
        secondary = Color(0xFF82A9FF), // Unread badge
        onSecondary = Color(0xFF071B43), // Unread badge text
        secondaryContainer = Color(0xFF18386F), // Navigation selector and secondary actions
        onSecondaryContainer = Color(0xFFDDE7FF),
        tertiary = Color(0xFF55DCC6), // Downloaded badge
        onTertiary = Color(0xFF003B34),
        tertiaryContainer = Color(0xFF07564D),
        onTertiaryContainer = Color(0xFF9CF5E5),
        background = Color(0xFF050C1B),
        onBackground = Color(0xFFF5F6FF),
        surface = Color(0xFF08142A),
        onSurface = Color(0xFFF5F6FF),
        surfaceVariant = Color(0xFF0D1A35), // Navigation and grouped surfaces
        onSurfaceVariant = Color(0xFFB6C2DE),
        surfaceTint = Color(0xFFAA8BFF),
        inverseSurface = Color(0xFFE8ECF8),
        inverseOnSurface = Color(0xFF10182A),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8393B7),
        outlineVariant = Color(0xFF2B416B),
        surfaceContainerLowest = Color(0xFF050C1B),
        surfaceContainerLow = Color(0xFF08142A),
        surfaceContainer = Color(0xFF0D1A35),
        surfaceContainerHigh = Color(0xFF122344),
        surfaceContainerHighest = Color(0xFF192B50),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF5F39C7),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE9DDFF),
        onPrimaryContainer = Color(0xFF26105B),
        inversePrimary = Color(0xFFAA8BFF),
        secondary = Color(0xFF315DAA), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFDDE7FF),
        onSecondaryContainer = Color(0xFF0D234E),
        tertiary = Color(0xFF007568), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFFC3F4EA),
        onTertiaryContainer = Color(0xFF00201B),
        background = Color(0xFFF5F6FC),
        onBackground = Color(0xFF10182A),
        surface = Color(0xFFF9F9FF),
        onSurface = Color(0xFF10182A),
        surfaceVariant = Color(0xFFE9ECF7),
        onSurfaceVariant = Color(0xFF46516A),
        surfaceTint = Color(0xFF5F39C7),
        inverseSurface = Color(0xFF273047),
        inverseOnSurface = Color(0xFFF5F6FC),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF69748E),
        outlineVariant = Color(0xFFD2D8E8),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7F8FE),
        surfaceContainer = Color(0xFFEFF1FA),
        surfaceContainerHigh = Color(0xFFE7EAF6),
        surfaceContainerHighest = Color(0xFFDDE2F0),
    )
}
