package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Default theme
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #2979FF
 * Secondary #2979FF
 * Tertiary #47A84A
 * Neutral #919094
 */
internal object TachiyomiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFF0B0FF),
        onPrimary = Color(0xFF4A006E),
        primaryContainer = Color(0xFF66009B),
        onPrimaryContainer = Color(0xFFF9D9FF),
        inversePrimary = Color(0xFF8300CA),
        secondary = Color(0xFFF0B0FF), // Unread badge
        onSecondary = Color(0xFF4A006E), // Unread badge text
        secondaryContainer = Color(0xFF66009B), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(0xFFF9D9FF), // Navigation bar selector icon
        tertiary = Color(0xFFD7B899), // Downloaded badge
        onTertiary = Color(0xFF3B2A17), // Downloaded badge text
        tertiaryContainer = Color(0xFF54402A),
        onTertiaryContainer = Color(0xFFF3DCC0),
        background = Color(0xFF1B1B1F),
        onBackground = Color(0xFFE3E2E6),
        surface = Color(0xFF1B1B1F),
        onSurface = Color(0xFFE3E2E6),
        surfaceVariant = Color(0xFF211F26), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFC5C6D0),
        surfaceTint = Color(0xFFF0B0FF),
        inverseSurface = Color(0xFFE3E2E6),
        inverseOnSurface = Color(0xFF1B1B1F),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8F9099),
        outlineVariant = Color(0xFF44464F),
        surfaceContainerLowest = Color(0xFF1A181D),
        surfaceContainerLow = Color(0xFF1E1C22),
        surfaceContainer = Color(0xFF211F26), // Navigation bar background
        surfaceContainerHigh = Color(0xFF292730),
        surfaceContainerHighest = Color(0xFF302E38),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF8300CA),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFF9D9FF),
        onPrimaryContainer = Color(0xFF320045),
        inversePrimary = Color(0xFFF0B0FF),
        secondary = Color(0xFF8300CA), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFF9D9FF), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFF320045), // Navigation bar selector icon
        tertiary = Color(0xFF7A5A36), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFFF3DCC0),
        onTertiaryContainer = Color(0xFF2A1800),
        background = Color(0xFFFFFBFC),
        onBackground = Color(0xFF1B1B1F),
        surface = Color(0xFFFFFBFC),
        onSurface = Color(0xFF1B1B1F),
        surfaceVariant = Color(0xFFF7EDF0), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF44464F),
        surfaceTint = Color(0xFF8300CA),
        inverseSurface = Color(0xFF303034),
        inverseOnSurface = Color(0xFFF4F0F2),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF757780),
        outlineVariant = Color(0xFFC5C6D0),
        surfaceContainerLowest = Color(0xFFF8F1F3),
        surfaceContainerLow = Color(0xFFFAF2F4),
        surfaceContainer = Color(0xFFF7EDF0), // Navigation bar background
        surfaceContainerHigh = Color(0xFFFFF7F9),
        surfaceContainerHighest = Color(0xFFFFF7F9),
    )
}
